### ISSUE TITLE
BOT is not working

### ISSUE THREAD

**Issue by deepakksharma00079** [AnjanaMadu/TGForward#4]
showing H10 error app crashed.. my telegram username is @markzuker
please help me

**Comment by AnjanaMadu** [comment]
Thats not related to repo. Thats problem with heroku. Redeploy and try again.

**Comment by deepakksharma00079** [comment]
> Thats not related to repo. Thats problem with heroku. Redeploy and try again.
I have done all as you told but it's showing the same. Please help
